# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vcare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vcare

  # SwiftLint
  pod 'SwiftLint', '~> 0.27'
  
  # Fierbase
  pod 'FirebaseUI'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  
  # Tool
  pod 'ProgressHUD'
  pod 'SDWebImage'
  pod 'MGSwipeTableCell'

end
